export const FACEBOOK_LOGIN = 'FACEBOOK_LOGIN';
export const TWITTER_LOGIN = 'FETCH_ORDERS_SUCCESS';
export const GOOGLE_LOGIN = 'GOOGLE_LOGIN';
export const USERNAME_PASSWORD_LOGIN = 'USERNAME_PASSWORD_LOGIN';
export const USERNAME_PASSWORD_SIGNUP= 'USERNAME_PASSWORD_SIGNUP';